### PR TITLE
Rename stats > StatsCommand

### PR DESCRIPTION
**Pull request by Milo123459**
My OCD made me create this PR changing statsCommand.ts to StatsCommand.ts

### CODE REVIEW

**Comment by Cy1der** [comment]
b r u h

**Comment by Milo123459** [comment]
m e r g e

**Comment by Cy1der** [comment]
you made a pr just to capitalize a word



b r u h

**Comment by Milo123459** [comment]
there are more commands like this so you are lucky I haven't made more

**Comment by Cy1der** [comment]
i merged

**Comment by Milo123459** [comment]
hold that thought you are getting more prs fixing the names

**Comment by Milo123459** [comment]
> i merged

i saw

**Pull request merged**
